version: "3.9"

services:
  db:
    image: postgres

    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_DB_NAME
      - POSTGRES_USER=$POSTGRES_DB_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASS
    ports:
      - "5432:5432"
  web:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Bulletin_board
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB_NAME=$POSTGRES_DB_NAME
      - POSTGRES_DB_USER=$POSTGRES_DB_USER
      - POSTGRES_PASS=$POSTGRES_PASS
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - DEBUG=$DEBUG
    depends_on:
      - db
volumes:
  pgdata:
