version: "3.9"

services:
  mongo:
    image: mongo:6.0.3
    env_file:
      - .env
    volumes:
      - mongodata:/var/lib/mongo/data
    ports:
      - "27017:27017"
    networks:
      - net
  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - net
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - redisdata:/var/lib/redis/data
    networks:
      - net
  web:
    tty: true
    build:
      context: .
    command: gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --reload
    volumes:
      - .:/zmall
      - static:/zmall/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - net
    depends_on:
      - postgres
<<<<<<< HEAD
=======
  nginx:
    restart: always
    image: nginx:1.19.8
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/zmall/static
    ports:
      - "80:80"
    networks:
      - net
    depends_on:
      - web
>>>>>>> 420f9660c278aebed21a2a8f1ca5ce670068b81c
  celery:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/zmall
    depends_on:
      - postgres
      - redis
    networks:
      - net
  celery-beat:
    build: .
    command: celery -A config beat -l info
    volumes:
      - .:/zmall
    depends_on:
      - postgres
      - redis
    networks:
      - net
volumes:
  pgdata:
  mongodata:
  redisdata:
  static:
networks:
  net: {}
