version: "3.9"

services:
  db:
    image: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=$POSTGRES_DB_NAME
      - POSTGRES_USER=$POSTGRES_DB_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASS
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Bulletin_board
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB_NAME=$POSTGRES_DB_NAME
      - POSTGRES_DB_USER=$POSTGRES_DB_USER
      - POSTGRES_PASS=$POSTGRES_PASS
    depends_on:
      - db
volumes:
  postgres_data: