version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - zmall_net
  web:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Bulletin_board
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - zmall_net
    depends_on:
      - db
volumes:
  pgdata:
networks:
  zmall_net: {}
